services:
  - type: web
    name: storyli-api
    runtime: node
    region: frankfurt
    repo: https://github.com/sbenfares/storyli
    branch: main
    buildCommand: cd packages/api && yarn install --immutable && yarn build
    startCommand: cd packages/api && yarn start
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: DATABASE_URL
        sync: false
      - key: PORT
        value: 3001
      - key: NODE_ENV
        value: production
